// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Built-in datasets.
 *
 * OUDE KORENDIJK is a real, published aquifer test carried out in 1963 in a
 * polder south of Rotterdam (de Wit 1963), published in Kruseman & de Ridder,
 * "Analysis and Evaluation of Pumping Test Data", ILRI Publication 47. It is
 * the standard worked example in the field. The time-drawdown values here were
 * transcribed from the TTim project (MIT licensed, Mark Bakker,
 * github.com/mbakker7/ttim), which distributes them as
 * docs/03pumpingtests/data/piezometer_h30.txt and piezometer_h90.txt. Their
 * files record head change, which is negative; the sign is inverted here so
 * these are drawdowns.
 *
 * Test conditions: constant discharge 788 m3/d for roughly 14 hours, confined
 * aquifer 7 m thick, piezometers at 30 m and 90 m.
 *
 * The other two datasets are SYNTHETIC. They were generated by evaluating the
 * models in this repository at stated parameters and adding pseudo-random
 * noise from a fixed seed. They are useful for demonstrating the tool and for
 * regression tests, and they prove nothing about real aquifers.
 */

import type { TestSetup } from "./types";

export interface Sample {
  id: string;
  name: string;
  provenance: string;
  synthetic: boolean;
  setup: TestSetup;
  /** What an independent, published analysis reported, where one exists. */
  published?: string;
}

const OUDE_KORENDIJK_30 = [
    { t: 0.1, s: 0.040 },
    { t: 0.25, s: 0.080 },
    { t: 0.5, s: 0.130 },
    { t: 0.7, s: 0.180 },
    { t: 1, s: 0.230 },
    { t: 1.4, s: 0.280 },
    { t: 1.9, s: 0.330 },
    { t: 2.33, s: 0.360 },
    { t: 2.8, s: 0.390 },
    { t: 3.36, s: 0.420 },
    { t: 4, s: 0.450 },
    { t: 5.35, s: 0.500 },
    { t: 6.8, s: 0.540 },
    { t: 8.3, s: 0.570 },
    { t: 8.7, s: 0.580 },
    { t: 10, s: 0.600 },
    { t: 13.1, s: 0.640 },
    { t: 18, s: 0.680 },
    { t: 27, s: 0.742 },
    { t: 33, s: 0.753 },
    { t: 41, s: 0.779 },
    { t: 48, s: 0.793 },
    { t: 59, s: 0.819 },
    { t: 80, s: 0.855 },
    { t: 95, s: 0.873 },
    { t: 139, s: 0.915 },
    { t: 181, s: 0.935 },
    { t: 245, s: 0.966 },
    { t: 300, s: 0.990 },
    { t: 360, s: 1.007 },
    { t: 480, s: 1.050 },
    { t: 600, s: 1.053 },
    { t: 728, s: 1.072 },
    { t: 830, s: 1.088 },
];

const OUDE_KORENDIJK_90 = [
    { t: 1.5, s: 0.015 },
    { t: 2, s: 0.021 },
    { t: 2.16, s: 0.023 },
    { t: 2.66, s: 0.044 },
    { t: 3, s: 0.054 },
    { t: 3.5, s: 0.075 },
    { t: 4, s: 0.090 },
    { t: 4.33, s: 0.104 },
    { t: 5.5, s: 0.133 },
    { t: 6, s: 0.153 },
    { t: 7.5, s: 0.178 },
    { t: 9, s: 0.206 },
    { t: 13, s: 0.250 },
    { t: 15, s: 0.275 },
    { t: 18, s: 0.305 },
    { t: 25, s: 0.348 },
    { t: 30, s: 0.364 },
    { t: 40, s: 0.404 },
    { t: 53, s: 0.429 },
    { t: 60, s: 0.444 },
    { t: 75, s: 0.467 },
    { t: 90, s: 0.494 },
    { t: 105, s: 0.507 },
    { t: 120, s: 0.528 },
    { t: 150, s: 0.550 },
    { t: 180, s: 0.569 },
    { t: 248, s: 0.593 },
    { t: 301, s: 0.614 },
    { t: 363, s: 0.636 },
    { t: 422, s: 0.657 },
    { t: 542, s: 0.679 },
    { t: 602, s: 0.688 },
    { t: 680, s: 0.701 },
    { t: 785, s: 0.718 },
    { t: 845, s: 0.716 },
];

/** Deterministic pseudo-random noise so the synthetic sets never move between builds. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function logSpacedMinutes(from: number, to: number, count: number): number[] {
  const out: number[] = [];
  const a = Math.log10(from);
  const b = Math.log10(to);
  for (let i = 0; i < count; i++) out.push(Number((10 ** (a + ((b - a) * i) / (count - 1))).toPrecision(3)));
  return out;
}

/** Synthetic confined test: T = 250 m2/d, S = 5e-4, Q = 1200 m3/d, r = 45 m. */
function syntheticConfined() {
  const rand = mulberry32(20260727);
  const T = 250 / 86400;
  const S = 5e-4;
  const Q = 1200 / 86400;
  const r = 45;
  return logSpacedMinutes(1, 1440, 28).map((minutes) => {
    const t = minutes * 60;
    const u = (r * r * S) / (4 * T * t);
    // Inline Theis so this file has no import cycle with models.ts.
    let w: number;
    if (u < 1) {
      w = -Math.log(u) - 0.5772156649015329;
      let fact = 1;
      for (let i = 1; i <= 60; i++) {
        fact *= -u / i;
        w += -fact / i;
      }
    } else {
      w = 0;
    }
    const s = (Q / (4 * Math.PI * T)) * w;
    const noise = (rand() - 0.5) * 0.012;
    return { t: minutes, s: Number(Math.max(s + noise, 0.001).toFixed(3)) };
  });
}

const SYNTHETIC_CONFINED = syntheticConfined();

export const SAMPLES: Sample[] = [
  {
    id: 'oude-korendijk',
    name: 'Oude Korendijk, Netherlands (1963)',
    provenance:
      'de Wit (1963), published in Kruseman & de Ridder, ILRI Publication 47. Values transcribed from the TTim project (MIT).',
    synthetic: false,
    published:
      'AQTESOLV, MLU and TTim all report k near 66 m/d and Ss near 2.5e-5 /m on the two piezometers fitted together, which for a 7 m aquifer is T near 463 m²/d and S near 1.8e-4.',
    setup: {
      Q: 788 / 86400,
      model: 'theis',
      piezometers: [
        {
          id: 'p30',
          label: 'P30',
          r: 30,
          readings: OUDE_KORENDIJK_30.map((d) => ({ t: d.t * 60, s: d.s })),
        },
        {
          id: 'p90',
          label: 'P90',
          r: 90,
          readings: OUDE_KORENDIJK_90.map((d) => ({ t: d.t * 60, s: d.s })),
        },
      ],
    },
  },
  {
    id: 'synthetic-confined',
    name: 'Synthetic confined test',
    provenance: 'Generated by this repository. Theis at T = 250 m²/d, S = 5e-4, Q = 1200 m³/d, r = 45 m, plus 12 mm of noise.',
    synthetic: true,
    published: 'Not a real test. The correct answer is T = 250 m²/d and S = 5e-4 by construction.',
    setup: {
      Q: 1200 / 86400,
      model: 'theis',
      piezometers: [
        {
          id: 'obs',
          label: 'OBS-1',
          r: 45,
          readings: SYNTHETIC_CONFINED.map((d) => ({ t: d.t * 60, s: d.s })),
        },
      ],
    },
  },
];

export const RAW_SAMPLE_TABLES: Record<string, Record<string, Array<{ t: number; s: number }>>> = {
  'oude-korendijk': { p30: OUDE_KORENDIJK_30, p90: OUDE_KORENDIJK_90 },
  'synthetic-confined': { obs: SYNTHETIC_CONFINED },
};
